torchrun --nproc_per_node 3 finetuning.py \
    --model Llama7B_adapter \
    --llama_model_path /barn6/yilinsong/LLaMA-Adapter/alpaca_finetuning_v1/test/ \
    --data_path /barn6/yilinsong/LLaMA-Adapter/data/alpaca_data.json \
    --adapter_layer 30 \
    --adapter_len 10 \
    --max_seq_len 512 \
    --batch_size 1 \
    --epochs 5 \
    --warmup_epochs 2 \
    --blr 9e-3 \
    --weight_decay 0.02 \
    --output_dir ./checkpoint/
